"""End-to-end tests against the real Seamly2D binaries.

Skipped automatically when the binaries are not available (see config.py for
the lookup order). These are the authoritative Phase-0 gates.
"""

from pathlib import Path

from conftest import needs_seamly2d, needs_seamlyme

from pattern_forge.recipes import AlineSkirt
from pattern_forge.seamly_cli import (
    ExportFormat,
    export_pattern,
    validate_measurements,
    validate_pattern,
)
from pattern_forge.smis import MeasurementsFile

DATA = Path(__file__).parent / "data"


@needs_seamly2d
def test_gate_generated_skirt_computes(tmp_path):
    """PHASE 0 GATE: a pattern generated by our writer is accepted by real Seamly2D."""
    doc = AlineSkirt().draft({"waist_circ": 90})
    path = doc.save(tmp_path / "skirt.sm2d")
    result = validate_pattern(path)
    assert result.ok, f"exit {result.exit_code} ({result.meaning})\n{result.stderr}\n{result.stdout}"


@needs_seamly2d
def test_shipped_trousers_sample_validates():
    """Sanity check of the CLI wrapper itself, using Seamly2D's own sample files."""
    result = validate_pattern(DATA / "trousers.sm2d", measurements=DATA / "trousers.smis")
    assert result.ok, f"exit {result.exit_code} ({result.meaning})\n{result.stderr}"


@needs_seamly2d
def test_export_shipped_trousers_to_svg(tmp_path):
    """Export path works end-to-end (the trousers sample has pieces, so it can export)."""
    result = export_pattern(
        DATA / "trousers.sm2d",
        out_dir=tmp_path,
        basename="preview",
        fmt=ExportFormat.SVG,
        measurements=DATA / "trousers.smis",
    )
    assert result.ok, f"exit {result.exit_code} ({result.meaning})\n{result.stderr}"
    assert result.produced, "no SVG files were produced"


@needs_seamly2d
def test_broken_formula_is_caught(tmp_path):
    """A wrong formula must fail validation — not pass silently.

    Observed behavior of the real binary: formula errors hit during file LOAD
    exit with 66 (file treated as unreadable); errors during later
    recalculation exit with 65. Both are failures; accept either.
    """
    doc = AlineSkirt().draft({"waist_circ": 90})
    xml = doc.to_string().replace("#WaistCirc/4", "#DoesNotExist/4")
    bad = tmp_path / "broken.sm2d"
    bad.write_text(xml, encoding="utf-8")
    result = validate_pattern(bad)
    assert not result.ok
    assert result.exit_code in (65, 66), f"expected 65/66, got {result.exit_code}"
    assert "DoesNotExist" in result.stderr, "error message should name the bad token"


@needs_seamly2d
def test_export_never_touches_other_basenames(tmp_path):
    """REGRESSION (review finding): the stale-file cleanup must not delete files
    of another pattern whose basename merely starts with this one's."""
    decoy = tmp_path / "skirt_other_pieces.svg"
    decoy.write_text("do not delete me", encoding="utf-8")
    doc = AlineSkirt().draft({"waist_circ": 90})
    path = doc.save(tmp_path / "p.sm2d")
    result = export_pattern(path, tmp_path, "skirt", ExportFormat.SVG)
    assert result.ok
    assert decoy.exists(), "cleanup deleted an unrelated file (prefix collision)"
    assert all("skirt_other" not in f.name for f in result.produced), (
        "produced list claimed another pattern's files"
    )


@needs_seamlyme
def test_generated_smis_validates(tmp_path):
    """A measurements file generated by our writer is accepted by real SeamlyMe."""
    m = MeasurementsFile(unit="cm")
    m.set_many({"waist_circ": 84, "hip_circ": 100})
    path = m.save(tmp_path / "client.smis")
    result = validate_measurements(path)
    assert result.ok, f"exit {result.exit_code} ({result.meaning})\n{result.stderr}"
