"""Demo recipe: A-line skirt front block (quarter pattern, cut on fold).

Phase-0 proof recipe: minimal but honest — parametric via increments, curved
waist and hem. The full production recipe (trousers) lands in Phase 1.
"""

from __future__ import annotations

from ..sm2d import Document
from .base import MeasurementSpec, OptionSpec, Recipe


class AlineSkirt(Recipe):
    name = "aline_skirt"
    description = "A-line skirt front block (quarter pattern, cut on fold). Unit: cm."

    required_measurements = [
        MeasurementSpec("waist_circ", 40, 200, "waist circumference"),
    ]

    options = [
        OptionSpec("skirt_length", default=60, min_value=20, max_value=120,
                   description="waist to hem"),
        OptionSpec("waist_ease", default=1, min_value=0, max_value=6,
                   description="ease added to the full waist"),
        OptionSpec("flare", default=8, min_value=0, max_value=30,
                   description="extra width at the hem side (A-line amount)"),
    ]

    def build(self, measurements: dict[str, float], options: dict[str, float]) -> Document:
        doc = Document(
            unit="cm",
            description=(
                "A-line skirt front block generated by pattern-forge. "
                "Edit #WaistCirc / #SkirtLength / #Flare in the Variables table (Ctrl+T) "
                "and the pattern recalculates."
            ),
        )

        # Parametric variables: the geometry below references these by name,
        # so the pattern stays editable/re-gradable inside Seamly2D.
        waist = doc.add_increment(
            "#WaistCirc",
            measurements["waist_circ"] + options["waist_ease"],
            "waist circumference incl. ease",
        )
        length = doc.add_increment("#SkirtLength", options["skirt_length"], "waist to hem")
        flare = doc.add_increment("#Flare", options["flare"], "extra width at hem side")

        block = doc.add_draft_block("Skirt")

        waist_center = block.add_base_point("WaistCenter", x=1, y=1, mx=-1.5, my=-2.5)
        waist_side = block.add_end_line_point(
            "WaistSide", base=waist_center, angle=0, length=f"{waist}/4",
            mx=0.8, my=-2.5,
        )
        hem_center = block.add_end_line_point(
            "HemCenter", base=waist_center, angle=270, length=length,
            line_type="solidLine", mx=-3.5, my=0.8,
        )
        hem_side = block.add_end_line_point(
            "HemSide", base=hem_center, angle=0, length=f"{waist}/4 + {flare}",
            mx=0.8, my=0.8,
        )

        # side seam
        block.add_line(waist_side, hem_side)
        # waist curve: leaves center front perpendicular, rises slightly at the side
        block.add_simple_spline(waist_center, waist_side,
                                angle1=0, angle2=183, length1=8, length2=8)
        # hem curve: gentle sweep, rises slightly at the side seam
        block.add_simple_spline(hem_center, hem_side,
                                angle1=0, angle2=183, length1=12, length2=12)

        return doc
